#!/usr/bin/env bash
# install.sh — Interactive Infy Messenger deployment on Ubuntu VPS
# Usage: curl -fsSL https://raw.../install.sh | sudo bash
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
section() { echo -e "\n${CYAN}══ $* ══${NC}"; }

# ── 1. Root check ────────────────────────────────────────────
section "Checking permissions"
if [[ $EUID -ne 0 ]]; then
    error "Run as root or with sudo: sudo bash install.sh"
fi

# ── 2. OS check ──────────────────────────────────────────────
if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then
    warn "This script is designed for Ubuntu. Proceed with caution on other distros."
fi

# ── 3. Install Docker ────────────────────────────────────────
section "Installing Docker Engine"
if command -v docker &>/dev/null; then
    info "Docker already installed: $(docker --version)"
else
    info "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
    info "Docker installed: $(docker --version)"
fi

# ── 4. Interactive prompts ────────────────────────────────────
section "Configuration"

read -rp "Base domain (e.g. example.com): " DOMAIN
[[ -z "$DOMAIN" ]] && error "Domain cannot be empty"

read -rp "Email for Let's Encrypt (for cert expiry notifications): " LE_EMAIL
[[ -z "$LE_EMAIL" ]] && error "Email cannot be empty"

read -rsp "Password for first ADMIN account: " ADMIN_PASSWORD
echo
[[ ${#ADMIN_PASSWORD} -lt 8 ]] && error "Admin password must be at least 8 characters"

# ── 5. DNS check ─────────────────────────────────────────────
section "Checking DNS resolution"
SERVER_IP=$(curl -4 -fsSL https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
info "Detected server IP: $SERVER_IP"

DNS_OK=true
for sub in app api ws media; do
    SUBDOMAIN="${sub}.${DOMAIN}"
    RESOLVED=$(dig +short "$SUBDOMAIN" A 2>/dev/null | tail -1)
    if [[ "$RESOLVED" == "$SERVER_IP" ]]; then
        info "  ✓ ${SUBDOMAIN} → ${RESOLVED}"
    else
        warn "  ✗ ${SUBDOMAIN} resolves to '${RESOLVED:-<nothing>}', expected ${SERVER_IP}"
        DNS_OK=false
    fi
done

if [[ "$DNS_OK" != true ]]; then
    echo
    warn "Some DNS records do not point to this server."
    warn "Please create A records for app/api/ws/media.${DOMAIN} → ${SERVER_IP}"
    warn "DNS propagation can take up to 48h."
    read -rp "Continue anyway (certbot will fail if DNS is wrong)? [y/N] " CONT
    [[ "$CONT" =~ ^[Yy]$ ]] || error "Aborted. Fix DNS first."
fi

# ── 6. Firewall (ufw) ────────────────────────────────────────
section "Configuring firewall"
if command -v ufw &>/dev/null; then
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow 22/tcp   comment 'SSH'
    ufw allow 80/tcp   comment 'HTTP'
    ufw allow 443/tcp  comment 'HTTPS'
    ufw --force enable
    info "ufw enabled: SSH, HTTP, HTTPS allowed"
else
    warn "ufw not found — skipping firewall configuration"
fi

# ── 7. Generate secrets ──────────────────────────────────────
section "Generating secrets"

INSTALL_DIR="/opt/infy"
mkdir -p "$INSTALL_DIR"

JWT_ACCESS_SECRET=$(openssl rand -hex 64)
JWT_REFRESH_SECRET=$(openssl rand -hex 64)
DB_PASSWORD=$(openssl rand -hex 24)
MINIO_PASSWORD=$(openssl rand -hex 24)

cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_DB=infy
POSTGRES_USER=infy
POSTGRES_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://infy:${DB_PASSWORD}@postgres:5432/infy

REDIS_URL=redis://redis:6379

JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=30d

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET_AVATARS=avatars
MINIO_BUCKET_MEDIA=media
MINIO_PUBLIC_URL=https://media.${DOMAIN}

DOMAIN=${DOMAIN}

RATE_LIMIT_REGISTER_MAX=5
RATE_LIMIT_REGISTER_WINDOW_MS=3600000
RATE_LIMIT_LOGIN_MAX=10
RATE_LIMIT_LOGIN_WINDOW_MS=900000
RATE_LIMIT_GLOBAL_MAX=100
RATE_LIMIT_GLOBAL_WINDOW_MS=60000

NODE_ENV=production
LOG_LEVEL=info
CORS_ORIGINS=https://app.${DOMAIN}
TRUSTED_PROXY=172.0.0.0/8
EOF

chmod 600 "$INSTALL_DIR/.env"
info "Secrets written to $INSTALL_DIR/.env"

# ── 8. Copy project files ────────────────────────────────────
section "Setting up project"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$SCRIPT_DIR" != "$INSTALL_DIR" ]]; then
    cp -r "$SCRIPT_DIR/." "$INSTALL_DIR/"
    info "Project files copied to $INSTALL_DIR"
fi

# Swap nginx config for prod
cp "$INSTALL_DIR/nginx/prod.conf" /tmp/nginx-prod.conf
sed -i "s/DOMAIN/${DOMAIN}/g" /tmp/nginx-prod.conf
cp /tmp/nginx-prod.conf "$INSTALL_DIR/nginx/active.conf"

# Point docker-compose to prod nginx config
sed -i 's|nginx/dev.conf|nginx/active.conf|g' "$INSTALL_DIR/docker-compose.yml"

cd "$INSTALL_DIR"

# ── 9. Start containers ──────────────────────────────────────
section "Starting containers"
docker compose up -d --build
info "Containers started"

# ── 10. TLS via certbot ──────────────────────────────────────
section "Obtaining TLS certificates"

if ! command -v certbot &>/dev/null; then
    apt-get install -y -qq certbot python3-certbot-nginx
fi

for sub in app api ws media; do
    SUBDOMAIN="${sub}.${DOMAIN}"
    info "Requesting cert for $SUBDOMAIN..."
    certbot certonly --webroot \
        --webroot-path=/var/www/certbot \
        --email "$LE_EMAIL" \
        --agree-tos \
        --no-eff-email \
        --non-interactive \
        -d "$SUBDOMAIN" \
        || warn "Failed to obtain cert for $SUBDOMAIN (check DNS)"
done

# Auto-renewal
if systemctl is-active --quiet systemd; then
    systemctl enable --now certbot.timer 2>/dev/null || \
    (crontab -l 2>/dev/null; echo "0 0,12 * * * certbot renew --quiet --post-hook 'docker compose -f $INSTALL_DIR/docker-compose.yml exec nginx nginx -s reload'") | crontab -
    info "Auto-renewal configured"
fi

# Reload nginx with TLS config
docker compose exec nginx nginx -s reload 2>/dev/null || true

# ── 11. Run Prisma migrations ────────────────────────────────
section "Running database migrations"
docker compose exec core npx prisma migrate deploy
info "Migrations applied"

# ── 12. Create first ADMIN account ──────────────────────────
section "Creating admin account"
docker compose exec core node -e "
const { PrismaClient } = require('@prisma/client');
const argon2 = require('argon2');
async function main() {
  const prisma = new PrismaClient();
  const hash = await argon2.hash('${ADMIN_PASSWORD}');
  const user = await prisma.user.upsert({
    where: { username: 'admin' },
    create: {
      username: 'admin',
      nickname: 'Administrator',
      passwordHash: hash,
      role: 'ADMIN',
    },
    update: {},
  });
  console.log('Admin user id:', user.id);
  await prisma.\$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
"
info "Admin account created (username: admin)"

# ── 13. Done ─────────────────────────────────────────────────
section "Done!"
echo
echo -e "${GREEN}Infy Messenger is running!${NC}"
echo
echo "  App:   https://app.${DOMAIN}"
echo "  API:   https://api.${DOMAIN}/docs"
echo "  Admin: login with username 'admin'"
echo
echo "Useful commands:"
echo "  cd $INSTALL_DIR && docker compose logs -f"
echo "  docker compose ps"
echo "  docker compose restart core"
echo
warn "Keep $INSTALL_DIR/.env secure — it contains all secrets."
